/**
 * Staples for the pantry quick-picker. Also part of the vocabulary the
 * hand-typed pantry entry checks against, so a typo of a staple gets a
 * "did you mean" prompt even in a brand-new account with no imports yet.
 */
export const COMMON_ITEMS = [
  "salt",
  "black pepper",
  "olive oil",
  "vegetable oil",
  "butter",
  "eggs",
  "milk",
  "flour",
  "sugar",
  "brown sugar",
  "baking powder",
  "baking soda",
  "vanilla",
  "rice",
  "pasta",
  "noodles",
  "breadcrumbs",
  "oats",
  "canned tomatoes",
  "tomato paste",
  "chicken stock",
  "vegetable stock",
  "soy sauce",
  "vinegar",
  "honey",
  "maple syrup",
  "hot sauce",
  "mayonnaise",
  "mustard",
  "ketchup",
  "garlic powder",
  "onion powder",
  "paprika",
  "cumin",
  "oregano",
  "cinnamon",
  "chili flakes",
  "cornstarch",
  "peanut butter",
  "beans",
  "lentils",
];
